(function(){
  const App = window.App = window.App || {}; const S = App.state;
  App.ui = App.ui || {};
  const $ = s=>document.querySelector(s);

  App.ui.init=function(){ $('#concept').addEventListener('change', e=>switchConcept(e.target.value)); App.anim.init(); bindCpu(); bindPC(); bindBankers(); bindTimeline(); switchConcept('cpu-scheduling'); };

  function switchConcept(c){ S.concept=c; S.runningAnim=false; $('#cpu-scheduling-ui').style.display=(c==='cpu-scheduling')?'block':'none'; $('#producer-consumer-ui').style.display=(c==='producer-consumer')?'block':'none'; $('#bankers-algorithm-ui').style.display=(c==='bankers-algorithm')?'block':'none'; $('#process-list-container').style.display=(c==='cpu-scheduling')?'block':'none'; if(c==='cpu-scheduling'){ App.anim.resetCpu(false); } else if(c==='producer-consumer'){ window.resetPC(); App.draw.drawAll(); } else if(c==='bankers-algorithm'){ generateMatrices(); App.draw.drawAll(); } }

  function bindCpu(){ const alg=$('#algorithm'), at=$('#arrival-time'), bt=$('#burst-time'), pr=$('#priority-input'), add=$('#add-process'), st=$('#start-animation'), ps=$('#pause-animation'), rs=$('#reset-animation'), tqWrap=$('#time-quantum-input'), tq=$('#time-quantum'); alg.addEventListener('change',()=>{ const rr=alg.value==='rr', prio=alg.value==='priority'; tqWrap.style.display=rr?'block':'none'; pr.style.display=prio?'inline-block':'none'; S.algorithm=alg.value; updateList(); }); add.addEventListener('click',()=>{ const avt=parseInt(at.value), bst=parseInt(bt.value), pv=parseInt(pr.value); if(isNaN(avt)||isNaN(bst)||bst<=0){ alert('Enter valid arrival and positive burst.'); return; } if(S.algorithm==='priority' && isNaN(pv)){ alert('Enter a valid priority.'); return; } S.processes.push({ id:S.processes.length+1, arrivalTime:avt, burstTime:bst, priority:isNaN(pv)?null:pv, remainingTime:bst, completionTime:0, waitingTime:0, turnaroundTime:0, state:'new' }); at.value=''; bt.value=''; pr.value=''; updateList(); }); st.addEventListener('click',()=>{ if(S.algorithm==='rr'){ const q=parseInt(tq.value); if(isNaN(q)||q<=0) return alert('Invalid time quantum'); S.timeQuantum=q; } App.anim.startCpu(); }); ps.addEventListener('click',App.anim.pause); rs.addEventListener('click',()=>{ App.anim.pause(); App.anim.resetCpu(false); updateList(); }); }
  function updateList(){ const ul=$('#queue'); ul.innerHTML=''; S.processes.forEach(p=>{ const li=document.createElement('li'); let t=`P${p.id}: AT=${p.arrivalTime}, BT=${p.burstTime}`; if(p.priority!==null && S.algorithm==='priority') t+=`, Prio=${p.priority}`; li.textContent=t; li.style.borderLeft=`5px solid ${App.config.colors[(p.id-1)%App.config.colors.length]}`; ul.appendChild(li); }); }

  function bindPC(){ const buf=$('#buffer-size'); $('#pc-start')?.addEventListener('click',()=>{ window.resetPC(); S.runningAnim=true; const step=()=>{ if(!S.runningAnim) return; App.algo.producerConsumerStep(); App.draw.drawAll(); requestAnimationFrame(step); }; step(); }); $('#pc-pause')?.addEventListener('click',()=>{ S.runningAnim=false; }); $('#pc-reset')?.addEventListener('click',()=>{ S.runningAnim=false; window.resetPC(); App.draw.drawAll(); }); window.resetPC=function(){ S.bufferSize=parseInt(buf.value)||5; S.buffer=[]; S.empty=S.bufferSize; S.full=0; S.mutex=1; S.producer.state='idle'; S.consumer.state='idle'; } }

  function bindBankers(){ $('#generate-matrices')?.addEventListener('click', generateMatrices); $('#check-safe-state')?.addEventListener('click', ()=>{ App.algo.checkSafeState(); App.draw.drawAll(); }); }
  function generateMatrices(){ const B=S.bankers, np=parseInt($('#num-processes').value)||5, nr=parseInt($('#num-resources').value)||3; B.nProc=np; B.nRes=nr; $('#allocation-matrix').innerHTML=matrix('alloc',np,nr); $('#max-matrix').innerHTML=matrix('max',np,nr); $('#available-vector').innerHTML=vector('avail',nr); B.allocation=readM('alloc',np,nr); B.max=readM('max',np,nr); B.available=readV('avail',nr); App.algo.computeNeed(); }
  function matrix(id,r,c){ let h='<table>'; for(let i=0;i<r;i++){ h+='<tr>'; for(let j=0;j<c;j++){ h+=`<td><input type="number" id="${id}-${i}-${j}" value="0" min="0" style="width: 40px;"></td>`;} h+='</tr>'; } return h+'</table>'; }
  function vector(id,c){ let h='<table><tr>'; for(let i=0;i<c;i++){ h+=`<td><input type="number" id="${id}-${i}" value="0" min="0" style="width: 40px;"></td>`;} return h+'</tr></table>'; }
  function readM(id,r,c){ const m=[]; for(let i=0;i<r;i++){ const row=[]; for(let j=0;j<c;j++){ row.push(parseInt(document.getElementById(`${id}-${i}-${j}`).value)||0);} m.push(row);} return m; }
  function readV(id,c){ const v=[]; for(let i=0;i<c;i++){ v.push(parseInt(document.getElementById(`${id}-${i}`).value)||0);} return v; }

  function bindTimeline(){ const s=$('#timeline-slider'), f=$('#follow-live'); s.addEventListener('input',()=>{ S.live=false; S.timelineIndex=parseInt(s.value)||0; App.anim.jumpTo(S.timelineIndex); App.anim.updateTimelineUI(); }); f.addEventListener('change',()=>{ S.live=f.checked; if(S.live){ App.anim.updateTimelineUI(); } }); }
})();
